-- Populate explanation_body for all 30 tasks with science content.
-- Content sourced from "30 Days to Thrive with ADHD" reference guide.
-- Formatted as concise markdown: bullet points, short paragraphs, informal tone.

UPDATE public.tasks SET explanation_body = E'## Why rotation works\n\n**Your ADHD brain craves novelty** — it gets bored fast, but not of *everything* at once.\n\n```\n🔄 Project A → bored → Project B → bored → Project C\n     ↑                                          |\n     └──────── feels fresh again! ───────────────┘\n```\n\n- Forcing one thing = drained & frustrated\n- Rotating = each thing gets a "break" and feels new when you return\n- You''re not flaky — you''re **wired for variety**\n\n> The trick isn''t discipline. It''s designing a system that works *with* your brain, not against it.'
WHERE "order" = 1;

UPDATE public.tasks SET explanation_body = E'## The science of urge surfing\n\nDopamine signals feel urgent — but they''re **temporary**.\n\n```\n  Urge intensity\n  ▲\n  │    /\\\n  │   /  \\\n  │  /    \\_____ fades on its own\n  │ /\n  └──────────────────→ time\n       ~90 seconds\n```\n\n- The craving **peaks then fades** — like a wave\n- If you don''t act on it, it passes in ~90 seconds\n- Each time you "surf" instead of obey, the next urge gets **weaker**\n\n> You''re not fighting the urge. You''re just watching it come and go — like weather.'
WHERE "order" = 2;

UPDATE public.tasks SET explanation_body = E'## Your morning dopamine tank\n\nYou wake up with a full tank. Every scroll, notification, and video **drains it** before the day starts.\n\n```\n  ☀️ Wake up:  ████████████ 100%\n  📱 Scroll:   ██████░░░░░░  50%\n  💻 Work:     ██░░░░░░░░░░  15%  ← everything feels flat\n```\n\n**vs.**\n\n```\n  ☀️ Wake up:  ████████████ 100%\n  💪 Exercise: ██████████░░  85%  ← earned dopamine\n  💻 Work:     ████████░░░░  70%  ← still engaged\n```\n\n- **Save your dopamine** for things that matter\n- Screens first thing = your brain''s reward budget, blown early\n- Even 30 minutes of delay makes a measurable difference'
WHERE "order" = 3;

UPDATE public.tasks SET explanation_body = E'## Habits bypass dopamine\n\nADHD brains can form habits just fine — we just often form the **wrong** ones.\n\n- Once a habit is in place, it runs on **autopilot**\n- No willpower needed — that''s the whole point\n- The trick: **design your environment** so the right action is the easiest one\n\n```\n  🧠 Willpower path:   See phone → resist → resist → fail\n  ⚙️ Habit path:       Phone in other room → don''t even think about it\n```\n\n**Stack new habits onto existing ones:**\n- Medication → next to toothbrush\n- Journal → on your pillow\n- Water → next to the kettle\n\n> Environment beats motivation. Every time.'
WHERE "order" = 4;

UPDATE public.tasks SET explanation_body = E'## Concentration is a muscle\n\nFocus isn''t a fixed trait — it''s a **skill you can train**.\n\n- These exercises work like reps at the gym\n- The harder it feels, the **more benefit** you''re getting\n- Even 5 minutes of deliberate focus practice builds real neural pathways\n\n```\n  Week 1:  🧠 ░░░░░░░░░░  (hard, mind wanders constantly)\n  Week 4:  🧠 ████░░░░░░  (easier, catch yourself faster)\n  Week 8:  🧠 ████████░░  (focus feels more natural)\n```\n\n**Two modes to train:**\n- **Visual focus** — count leaves, scan details (trains sustained attention)\n- **Auditory focus** — identify sounds rapidly (trains attention switching)\n\n> Your brain isn''t broken. It just hasn''t been trained the right way yet.'
WHERE "order" = 5;

UPDATE public.tasks SET explanation_body = E'## Time blindness is real\n\nADHD brains have **impaired internal clocks**. This isn''t laziness — it''s neurology.\n\n```\n  What you think:     "This will take 10 minutes"\n  What actually happens: 45 minutes later...\n```\n\n- We **overestimate** boring tasks ("ugh, that''ll take forever" → actually 12 min)\n- We **underestimate** fun tasks ("just 5 more minutes" → 2 hours gone)\n\n**The fix:** collect real data.\n\n- Track start time + end time for everything today\n- Your brain will **recalibrate** with accurate info\n- Future planning actually works when it''s based on reality\n\n> You''re not bad at time. Your brain just needs an external clock.'
WHERE "order" = 6;

UPDATE public.tasks SET explanation_body = E'## Executive function: your brain''s project manager\n\nADHD is fundamentally an **executive function disorder** — planning, working memory, and impulse control all struggle at once.\n\n```\n  🧠 Executive Function Controls:\n  ├── Planning         (what to do first?)\n  ├── Working memory   (hold info while using it)\n  ├── Impulse control  (don''t do that other thing)\n  ├── Task switching   (move between things smoothly)\n  └── Self-monitoring  (am I still on track?)\n```\n\nThe 5-step framework trains **all of these** simultaneously:\n\n1. **Pause** → impulse control\n2. **State goal** → working memory\n3. **Break it down** → planning\n4. **Mid-task check** → self-monitoring\n5. **Reflect after** → learning from experience\n\n> It''s a full workout for the part of your brain ADHD affects most.'
WHERE "order" = 7;

UPDATE public.tasks SET explanation_body = E'## Your nervous system has two modes\n\nADHD often keeps your body stuck in a **chronic low-level stress state**.\n\n```\n  ⚡ Sympathetic (fight/flight)     😌 Parasympathetic (rest/digest)\n  ├── Heart racing                  ├── Heart slows\n  ├── Shallow breathing             ├── Deep breathing\n  ├── Scattered attention           ├── Focused calm\n  └── Always "on"                   └── Recovery mode\n```\n\n**Two ways to flip the switch:**\n\n- **Intense exercise** → triggers a compensatory calm the moment you stop\n- **Alternate nostril breathing** → slows your exhale, which directly dials down the nervous system\n\nBoth are **clinically validated** for anxiety and stress. The sprint-then-stillness combo is especially powerful for ADHD because it gives restless energy somewhere to go *first*.'
WHERE "order" = 8;

UPDATE public.tasks SET explanation_body = E'## The exhale is the secret\n\nYour **amygdala** (the brain''s alarm center) is less regulated in ADHD — feelings hit faster, harder, and longer.\n\n```\n  Inhale  → activates sympathetic (energy UP)\n  Exhale  → activates parasympathetic (calm DOWN)\n\n  1:2 ratio = exhale is TWICE as long\n  = your calm system wins\n```\n\n**The progression:**\n- Start: 2 sec in → 4 sec out\n- Build: 4 sec in → 8 sec out\n- Goal:  8 sec in → 16 sec out\n\n⚠️ **Critical:** practice when you''re already calm. If you only try it mid-meltdown, it won''t work — the skill needs to be automatic *before* you need it.\n\n> Think of it like a fire drill. You practice calm so it''s ready when it counts.'
WHERE "order" = 9;

UPDATE public.tasks SET explanation_body = E'## Why ADHD + anxiety go together\n\nYour brain''s alarm system fires more easily **and** the brakes are weaker.\n\n```\n  Neurotypical:  Alarm 🔔 → Brake 🛑 → "I''m okay"\n  ADHD:          Alarm 🔔🔔🔔 → Brake 🛑? → spiral\n```\n\n**Mapping breaks the cycle:**\n\n| What I''m anxious about | Where it came from | What I''ll do differently |\n|---|---|---|\n| Missing deadline | Got yelled at in school | Set 3 small alarms |\n| Social event | Embarrassed myself once | Prepare 2 conversation starters |\n\n- Writing it out moves anxiety from your **amygdala** (reactive) to your **prefrontal cortex** (logical)\n- You stop just reacting and start **building new wiring**\n\n> You''re not anxious because you''re weak. Your alarm system is just louder than most.'
WHERE "order" = 10;

UPDATE public.tasks SET explanation_body = E'## The wound on top of ADHD\n\nGrowing up with untreated ADHD almost always leaves behind a quiet belief: **"I''m broken."**\n\n```\n  Childhood:  "Why can''t you just focus?"\n              "You''re so lazy"\n              "You''re smart but you don''t apply yourself"\n                    ↓\n  Adult belief:  "I''m fundamentally less capable"\n                    ↓\n  Behavior:  Avoid challenges, self-sabotage, shame spiral\n```\n\nThat belief **isn''t ADHD** — it''s a wound *on top of* ADHD. And it controls your choices more than you realize.\n\n- The conclusions you formed as a kid were **survival responses**\n- What''s changed since then? (Usually: a lot)\n- One small action today that pushes back = proof the old story is wrong\n\n> You''re not rewriting history. You''re updating the story with better data.'
WHERE "order" = 11;

UPDATE public.tasks SET explanation_body = E'## Meditation trains your weakest muscle\n\nYour **frontal lobes** control attention, impulse control, and emotion regulation — exactly what ADHD weakens most.\n\n```\n  Meditation = gym for your frontal lobes\n\n  🧠 Before:  Thought → react → thought → react → chaos\n  🧠 After:   Thought → notice → choose → respond\n```\n\n**Why Om chanting specifically?**\n\n- Creates strong **physical vibration** → concrete anchor for attention\n- Activates the **vagus nerve** → calms nervous system\n- Reduces **amygdala activity** (your alarm center quiets down)\n- Easier than silent meditation because your brain has something to *do*\n\n**Tips for ADHD brains:**\n- Half-open eyes > closed eyes (less mind-wandering)\n- Light background music is fine\n- Getting distracted isn''t failing — **noticing** the distraction is the exercise'
WHERE "order" = 12;

UPDATE public.tasks SET explanation_body = E'## Yoga Nidra: rest + rewiring\n\nYoga Nidra puts you in a **deeply relaxed but conscious state** — similar to the edge of sleep.\n\n```\n  Awake          Yoga Nidra zone         Asleep\n  ├──────────────┤ ← HERE ├──────────────┤\n  Full alertness   Receptive calm      Unconscious\n```\n\n**Why it works for ADHD:**\n\n- Your mind is **more receptive** to new beliefs in this state\n- Progressive muscle contraction → release **physically resets** your nervous system\n- It''s one of the rare practices that combines **rest + active rewiring**\n\n**The affirmation matters:**\n- Keep it personal and in your control\n- "I deserve to be well" > "I will be rich"\n- Repeat 3x at the end — your brain is most receptive right then\n\n> You''re not sleeping. You''re teaching your brain something new while it''s listening.'
WHERE "order" = 13;

UPDATE public.tasks SET explanation_body = E'## Unstructured time = distraction time\n\nWith ADHD, the moments that derail us are **usually predictable** — we just haven''t pre-loaded a response.\n\n```\n  Without a plan:\n  Transition moment → brain freezes → phone → 45 min gone\n\n  With a plan:\n  Transition moment → pre-loaded response → stay on track\n```\n\n**The key insight:** plan the *responses*, not the whole day.\n\n- Identify 1-2 specific moments where things go wrong\n- Write down what you''ll do instead — **before** the moment arrives\n- A written plan turns a reactive moment into an automatic one\n\n> You don''t need a perfect schedule. You need a plan for the 2-3 moments that matter most.'
WHERE "order" = 14;

UPDATE public.tasks SET explanation_body = E'## Your best days aren''t random\n\n**Positive Deviance principle:** the answer is already in your data.\n\n```\n  Good day ✓              Bad day ✗\n  ├── Slept 7+ hours      ├── Slept 5 hours\n  ├── No phone till 9am   ├── Scrolled in bed\n  ├── Walked to work      ├── Skipped breakfast\n  └── Worked in café      └── Worked from couch\n```\n\n- Your best days have a **formula** — find it and copy it\n- Go *before* the productivity: what did you do that morning? How did you sleep?\n- Who did you avoid or talk to? What *wasn''t* in your environment?\n\n> You already know what works. The task is to notice it and repeat it on purpose.'
WHERE "order" = 15;

UPDATE public.tasks SET explanation_body = E'## Why ADHD + sleep is so hard\n\nYour brain fights sleep for **specific neurological reasons:**\n\n```\n  🌙 Bedtime:\n  ├── Frontal lobes are TIRED → can''t quiet racing thoughts\n  ├── Day''s emotions surface → nothing else to distract from them\n  └── Blue light → destroys melatonin production\n```\n\n**Three mechanisms, pick one:**\n\n- **Dimming light** (sunset, no screens) → protects melatonin\n- **Mindless activity** before bed (walk, no podcast) → lets thoughts process\n- **Carb-heavy dinner** → triggers sleepiness through serotonin\n\n⚠️ Pick ONE mechanism to address. Trying everything at once is overwhelming and leads to doing nothing.\n\n> Better sleep = better focus, better mood, better impulse control. It''s the highest-leverage change you can make.'
WHERE "order" = 16;

UPDATE public.tasks SET explanation_body = E'## Why "just don''t do it" doesn''t work\n\nADHD brains don''t automatically calculate **future costs** — we just see the immediate reward.\n\n```\n  Neurotypical:  🍫 Want → "but I''ll feel bad after" → stop\n  ADHD:          🍫 Want → DO IT → ...wait why did I do that\n```\n\n**"Play the tape forward" fixes the gap:**\n\n- Consciously run the scenario forward:\n  - How will I feel in **5 minutes**?\n  - In **20 minutes**?\n  - In **an hour**?\n  - What situation will I have created?\n\n- Done repeatedly, this process **becomes automatic**\n- Like learning a language — deliberate practice until it clicks\n\n> You''re not building willpower. You''re building a thinking habit your brain skipped.'
WHERE "order" = 17;

UPDATE public.tasks SET explanation_body = E'## Your phone is designed to exploit you\n\nApps specifically target ADHD vulnerabilities: **novelty, dopamine hits, emotional triggers.**\n\n```\n  📱 App designer''s toolkit:\n  ├── Infinite scroll    → novelty addiction\n  ├── Push notifications → interrupt loop\n  ├── Red badges         → urgency trigger\n  └── Autoplay           → decision fatigue\n```\n\n**Your counter-toolkit:**\n\n- **Physical distance** (60+ sec away) → removes pull before impulse control activates\n- **Grayscale mode** → makes apps visually unrewarding\n- **Per-app time limits** (5-10 min) → creates friction\n- **Replacement behavior** → decide what you''ll do *instead*\n\n⚠️ Cutting a behavior without replacing it doesn''t stick. Always have a "instead I''ll..." ready.\n\n> It''s not about willpower vs. your phone. It''s about making the phone boring.'
WHERE "order" = 18;

UPDATE public.tasks SET explanation_body = E'## Your brain needs a baseline of stimulation\n\nADHD brains run on a **stimulation budget** — too little and your brain creates its own distractions.\n\n```\n  Too little input:  🧠 → generates own distractions (daydreaming, fidgeting)\n  Sweet spot:        🧠 → calm, focused, productive\n  Too much input:    🧠 → overwhelmed, shuts down\n```\n\n**Finding your sweet spot:**\n\n- **Sound:** background music without lyrics, café noise, white noise\n- **Touch:** fidget tools, textured surfaces\n- **Movement:** standing desk, walking meetings, treadmill work\n- **Visual:** clean workspace with one interesting object\n\nExperiment with **combinations** — writing emails on a treadmill, reading while fidgeting, coding in a café.\n\n> It''s not a character flaw. It''s neurology. The right input lets your brain settle and stay.'
WHERE "order" = 19;

UPDATE public.tasks SET explanation_body = E'## The ADHD eating mismatch\n\nADHD creates a specific pattern: **cravings very high, satisfaction very low.**\n\n```\n  Craving:      ████████████  (dopamine says GO)\n  Satisfaction: ██░░░░░░░░░░  (never quite enough)\n  Result:       eat more, chasing a reward that doesn''t arrive\n```\n\n**Three tools that target the root cause:**\n\n1. **Eat slowly, no screens** → savoring increases *real* satisfaction\n2. **Make junk food hard to access** → barriers buy time for impulse to pass\n3. **High-fiber, bulky foods** → triggers a physical "full" signal that suppresses dopamine-driven eating\n\n> This isn''t about restriction or guilt. It''s about closing the gap between craving and satisfaction.'
WHERE "order" = 20;

UPDATE public.tasks SET explanation_body = E'## Your gut makes your brain chemicals\n\nAbout **90% of serotonin** and a chunk of **dopamine** are produced in your gut.\n\n```\n  Gut bacteria → produce building blocks → 🧠 dopamine + serotonin\n\n  ADHD brains tend to have LOWER levels of:\n  • Bifidobacterium\n  • Lactobacillus\n  • Akkermansia\n```\n\n**Foods that feed the right bacteria:**\n\n- 🍌 Unripe bananas\n- 🥣 Oats or barley\n- 🌱 Flax or chia seeds\n- 🥦 Minimally processed fruits & veggies\n\nFeeding the right bacteria can:\n- Reduce **brain inflammation**\n- Support the **chemistry** your brain needs\n- Improve mood and focus **from the gut up**\n\n> Your brain doesn''t work alone. Your gut is its silent partner.'
WHERE "order" = 21;

UPDATE public.tasks SET explanation_body = E'## Ayurveda meets neuroscience\n\nAyurvedic medicine frames ADHD as excess **"Vata"** (wind energy) — scattered, fast-moving, hard to settle.\n\n```\n  Vata (wind):  scattered, restless, cold, dry\n       ↓\n  Counter with: warm, heavy, moist, grounding\n```\n\n**Simple swaps:**\n\n| Instead of... | Try... |\n|---|---|\n| Cold toast | Warm oatmeal |\n| Raw salad | Cooked soup |\n| Light snacks | Hearty stews |\n| Iced drinks | Warm tea |\n\n**The science connection:**\n- Dietary changes alter **gut bacteria**\n- Which influences **inflammation**\n- Which affects **neurotransmitter production**\n\nThe effect is slower than medication but potentially **longer-lasting**.\n\n> Ancient wisdom, modern mechanism. The food you eat changes your brain chemistry.'
WHERE "order" = 22;

UPDATE public.tasks SET explanation_body = E'## ADHD disrupts 5 social skills at once\n\n```\n  🧠 ADHD affects:\n  ├── Impulse control    (blurt things out)\n  ├── Attention           (zone out mid-conversation)\n  ├── Executive function  (forget commitments)\n  ├── Emotional regulation (overreact)\n  └── Empathy processing   (miss social cues)\n```\n\n**A structured apology trains ALL FIVE:**\n\n1. **Name what you did** → requires attention + honesty\n2. **Brief context, not excuses** → impulse control\n3. **Acknowledge their feelings** → empathy practice\n4. **Say what you''ll do differently** → executive planning\n5. **Listen** → emotional regulation\n\nIt''s also one of the most powerful **relationship repair tools** — and ADHD tends to strain relationships in ways that need repair.\n\n> You''re not apologizing because you''re broken. You''re building the skills ADHD makes harder.'
WHERE "order" = 23;

UPDATE public.tasks SET explanation_body = E'## Structural fixes for structural problems\n\nADHD makes conversation hard — we interrupt, zone out, forget what was said. **The fix isn''t "try harder."**\n\n```\n  🗣️ ADHD conversation struggles:\n  ├── Interrupt before they finish\n  ├── Zone out mid-sentence\n  ├── Forget what was just said\n  ├── Go on tangents\n  └── Blurt emotional reactions\n```\n\n**Environment fixes that help:**\n\n- **Right time & place** → don''t ambush people mid-task\n- **Sit side-by-side** (not across) → creates subconscious alliance\n- **Take notes** → compensates for attention gaps\n- **Walk together** → movement helps ADHD brains focus\n- **Schedule important talks** → prep time = better outcomes\n\n> These aren''t tricks or hacks. They''re removing friction *before* you even open your mouth.'
WHERE "order" = 24;

UPDATE public.tasks SET explanation_body = E'## Clutter is cognitive load\n\nYour brain **constantly scans** everything in your visual field — even unconsciously.\n\n```\n  Cluttered desk:   🧠 processing: 📱📚✏️🧴📎☕🗂️📦\n                    = less bandwidth for actual work\n\n  Clean desk:       🧠 processing: 💻\n                    = more bandwidth to focus\n```\n\n**Three rules that work:**\n\n1. **Clear your visual field** — remove anything "in progress" from sight\n2. **One item, one home** — pick ONE thing, give it a permanent spot, practice every time\n3. **Note distractions** — when something catches your eye mid-work, move it out of sight\n\n> Every object on your desk uses processing power. Less stuff to monitor = more bandwidth to focus.'
WHERE "order" = 25;

UPDATE public.tasks SET explanation_body = E'## Sequence matters more than you think\n\nADHD brains are **highly sensitive** to environment and order. The right sequence can flip a wasted day into a productive one.\n\n```\n  Experiment 1: Sequencing\n  Morning focused work → Afternoon meetings  ✓ or ✗?\n  Morning meetings → Afternoon focused work  ✓ or ✗?\n  → Find YOUR better order\n\n  Experiment 2: Breaks\n  Screen break:        😴 → return drained\n  Eyes-closed outside: 🧠 → return energized\n```\n\n**Why eyes-closed rest works:**\n\n- Your **eyes** are one of the biggest drains on brain resources\n- Even a few minutes of eyes-closed rest restores **frontal lobe energy**\n- Faster recovery than any screen break\n\n> Stop defaulting to phone-on-break. Close your eyes instead. Your brain will thank you.'
WHERE "order" = 26;

UPDATE public.tasks SET explanation_body = E'## Standard study methods weren''t built for you\n\nRe-reading is passive and barely works for **anyone**. For ADHD brains, it''s especially useless.\n\n**4 methods that actually work:**\n\n```\n  ❌ Re-read → passive → forgotten\n  ✅ Active methods → brain works harder → sticks\n```\n\n1. **Make it relevant** — "how could this be useful to *me*?"\n2. **Practice recall** — close the book, write what you remember, check, repeat 6x\n3. **One-page diagram** — organize everything onto a single blank page (the *making* is the learning)\n4. **Teach it** — pretend you have to explain it to someone else\n\nAll four methods force your brain to **actively process** the material. Active processing = real learning sticks.\n\n> You''re not bad at learning. The methods you were taught just weren''t designed for how your brain works.'
WHERE "order" = 27;

UPDATE public.tasks SET explanation_body = E'## An honest look at the numbers\n\nADHD medication is one of the **most studied and effective** treatments in all of psychiatry.\n\n```\n  📊 What the research shows:\n  ├── 30-40% symptom reduction on average\n  ├── Meaningful improvement in work, school, relationships\n  ├── One of the highest response rates of any psychiatric med\n  └── Personal choice — not a requirement\n```\n\n**The real barrier:**\n\n- It''s usually not the medication itself\n- It''s **starting the process** — finding a doctor, making the call\n- This task isn''t about committing to anything\n- It''s about **getting the conversation**\n\n> Whether you choose medication or not, make it an *informed* choice. Not one based on stigma or avoidance.'
WHERE "order" = 28;

UPDATE public.tasks SET explanation_body = E'## Therapy builds what medication can''t\n\nMedication treats symptoms. Therapy **builds skills**. The most effective approach combines both.\n\n```\n  💊 Medication:  reduces symptoms NOW\n  🧠 Therapy:     builds skills that LAST\n  💊+🧠 Both:     best outcomes in research\n```\n\n**What to look for:**\n\n- **Executive Function Training** — practical skill-building\n- **CBT for ADHD** — restructures thought patterns\n- Studies show **60%+ improvement** after a year of sticking with it\n\n**The shopping method:**\n\n1. Book 3 appointments with 3 different therapists\n2. See all three over 3 weeks\n3. Pick the one who fits best\n\n⚠️ Therapist fit matters **more** than the type of therapy. If it''s not working — tell them directly.\n\n> ADHD therapy isn''t about feelings. It''s about building the skills your brain finds hard.'
WHERE "order" = 29;

UPDATE public.tasks SET explanation_body = E'## Karma is just cause and effect\n\nYou didn''t choose your ADHD — that was inherited. But what you do with it from here is **entirely yours**.\n\n```\n  🌱 Seeds you''ve planted over 30 days:\n  ├── Awareness    (you see your patterns now)\n  ├── Tools        (you have techniques that work)\n  ├── Data         (you know what helps and what doesn''t)\n  └── Momentum     (you showed up, again and again)\n```\n\n**Your reflection questions:**\n\n- Which concepts hit **hardest**?\n- Which practices do you **actually want to keep**?\n- Which do you *know* you need but keep **avoiding**?\n\nThat short list = your next seeds to plant.\n\n> You won''t see the fruit overnight. But you already started — and that matters more than you think.'
WHERE "order" = 30;
